### ISSUE TITLE
Bug in Part 4

### ISSUE THREAD

**Issue by VirMol** [wadpac/GGIR#448] opened 2021-08-06 09:04 UTC
Dear all,
I have a the following bug : 
_Part 4
 1Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'C:/Users/PROMOD_CSV/Desktop/test/output_test/meta/ms3.out/NA', probable reason 'No such file or directory'_

BUT IMPORTANT thing :  I precise that this bug does not occure for every file I launch !
That's why I publish this bug, 
The strange thing is that for some .csv files in the same directory, no problem (= success for all of them).
And after , in another  directory , for antoher participant with 4 measure times (4 recording weeks/ one file= one week), with the same script and same naming model , I have for example 2 files ok and 2 files with this bug. ..
I can understand that it may be possible if my directoreies were not well mentionned but in my case, there is no logical bug !
Moreover, when I have a look on two csv files (one working after R script process and the other one with this bug message in red after processing), the 2 files are identical : same information  and there is acti data in both of them !
And when I copy/paste my csv files (one working/the another one not) in a folder on my desktop for example and I try again, same thing : the one whaich has worked before, works and the other one , not again...
I am really lost because , it does not make sense.

Thank you in advance if somebody had the same and has a solution for my problem.
regards,

Virginie

*

**Comment by vincentvanhees** [comment] 2021-09-08 12:04
I am closing this issue, because your message is not clear.

Please use the issue template when opening a new issue, which asks you to provide a reproducible description of the problem. This includes a detailed description of what you did, GGIR version, error messages in the console, a description of the part 2 output for the problematic files, and anything else you can think of that may help to understand your problem.

**Closed by vincentvanhees** 2021-09-08 12:04 UTC
