### ISSUE TITLE
g.part5 - day of interest can correspond to multiple lines

### ISSUE THREAD

**Issue by RubenBrondeel** [wadpac/GGIR#401] opened 2021-03-01 17:46 UTC
Hi,

Running g.part.5 I obtained the error below.
The direct cause is the same date of onset of 2 subsequent nights. This is caused by the setting 'ignorenonwear = TRUE' in g.sib.sum (g.part3). Due to invalid data in night 1, the sib.onset.time is within the same day as the sib.onset.time of the subsequent night. Therefore, when using the date in g.part5 to select the dayofinterest, 2 nights correspond. 

Errors and warnings for test.cwa.RData$message
[1] "number of items to replace is not a multiple of replacement length"

$call
dsummary[di, fi:(fi + 5)] <- c(summarysleep_tmp2$night[dayofinterst], 
    summarysleep_tmp2$daysleeper[dayofinterst], summarysleep_tmp2$cleaningcode[dayofinterst], 
    summarysleep_tmp2$guider[dayofinterst], summarysleep_tmp2$sleeplog_used[dayofinterst], 
    summarysleep_tmp2$acc_available[dayofinterst])

ps. In g.part5  I came across a typo reading the code in the code below. The summarysleep_tmp2 should probably be summarysleep_tmp, since summarysleep_tmp2 wasn't used before in the code. 

if (length(pko) > 0) {
  summarysleep_tmp = summarysleep_tmp2[-pko, 
  ]
}

**Comment by vincentvanhees** [comment] 2021-03-28 11:49
I am closing this issue now as I was not able to reproduce it, possible it has been fixed following pull requests #403 and #405.
Feel free to re-open if you see this error again.

**Closed by vincentvanhees** 2021-03-28 11:49 UTC
